name: agriculture_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  url_launcher: ^6.1.14
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  provider: ^6.1.2
  http: ^1.3.0
  flutter_spinkit: ^5.2.1
  animate_do: ^4.1.1
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  weather_icons: ^3.0.0
  carousel_slider: ^5.0.0
  path: ^1.8.3
  crypto: ^3.0.3
  shared_preferences: ^2.5.2
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flutter_launcher_icons: ^0.14.3
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  visibility_detector: ^0.4.0+2
  pdf: ^3.11.3
  syncfusion_flutter_charts: 28.2.12 # For graphs
  open_file: ^3.5.10
  intl: ^0.19.0
  image: ^4.0.2
  cloud_firestore: ^5.6.5
  firebase_database: ^11.3.4
  firebase_data_connect: ^0.1.3+2
  flutter_slidable: ^4.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/C.png
    - assets/agriculture_background.jpg
    - assets/login_background.jpg
    - assets/admin_background.jpg
    - assets/farmer_dashboard_bg.jpg
    - assets/Rainy.jpg
    - assets/cloudy.jpg
    - assets/sunny.jpg
    - assets/animated_rain.gif
    - assets/animated_cloud.gif
    - assets/animated_sun.gif
    - assets/animated_default.gif
    - assets/splash_bg.jpg
    - assets/farm_bg.jpg
    - assets/fertilizer_bg.jpg
    - assets/seeds_bg.jpg
    - assets/farm_background.jpg
    - assets/drip_irrigation_bg.jpg
    - assets/pesticide_bg.jpg
    - assets/models/soil_type_model.tflite
    - assets/test_soil.jpg
    - assets/models/labels.txt
    - assets/User_bg.jpg



flutter_icons:
    android: true
    ios: true
    image_path: "assets/c.png"
    adaptive_icon_background: "#ffffff"  # Background color (optional)
    adaptive_icon_foreground: "assets/c.png"  # Foreground image (optional)